version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: book_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./book-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    # Removido environment para evitar conflito com application.properties

  frontend:
    build:
      context: ./book-frontend/spa-book-register
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
